### ISSUE TITLE
UI is broken on Ubuntu 22.04

### ISSUE THREAD

**Issue by matteyeux** [cxnder/ksuite#11]
Hey,

I just built libksuite and the UI seems broken on Ubuntu 22.04. Not sure if the problem is Gnome (had the same issue with i3) or the fact that I have a 4K screen.

Here is what it looks like below
<img width="1920" alt="image" src="https://github.com/cxnder/ksuite/assets/8758978/4dd1a5a3-d967-4517-9d17-dee12cc772fc">

Btw, to build it on Linux I had to include string.h in `Views/SharedCache/VM.cpp` and replace `clang_64` by `gcc_64` in CMakeLists.txt:47

**Comment by cxnder** [comment]
I think there's actually two separate bugs here; Attempted to address them both

![image](https://github.com/cxnder/ksuite/assets/55725881/65a642e4-36c1-4fa9-93bc-68ed2da7e354)

First one (that huge gap) was I believe a side effect of improperly recreating some of the Qt UI glue nonsense, I've reworked that whole bit now and hopefully(?) it should be more stable. 

Second one (buttons being cut off) I'm not _super_ sure about? I'll need to figure out a way to repro that, but the latest commit might address it?

**Comment by matteyeux** [comment]
It looks far better 
<img width="1325" alt="image" src="https://github.com/cxnder/ksuite/assets/8758978/f15edaf4-f925-4b3f-acaf-792f925c63df">

Btw still had a build issue, gcc expects cstring instead of string.

```
ksuite/Views/SharedCache/VM.cpp:93:5: error: ‘memcpy’ was not declared in this scope
   93 |     memcpy(dest, (void *) &(((uint8_t *) m_mmap._mmap)[address]), length);
      |     ^~~~~~
ksuite/Views/SharedCache/VM.cpp:12:1: note: ‘memcpy’ is defined in header ‘<cstring>’; did you forget to ‘#include <cstring>’?
   11 | #include <fcntl.h>
  +++ |+#include <cstring>
   12 | #include <memory>
```

Anyway, closing the issue, thank you for the quick fix !
